{% set name = "hazelbean" %}
{% set version = "1.7.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hazelbean-{{ version }}.tar.gz
  sha256: 7e6d42b2f8d8d67d80fdcf18bd067b8ae145e87bb997b64d4c3ce150c4c9dac3
  patches:
    - 1.7.6-utils-fstring-patch.diff

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  #skip: true  # [py>=312]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >3                              # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - wheel
  host:
    - python
    - pip
    - cython >3
    - numpy
    - setuptools <70
    - setuptools_scm
    - wheel
  run:
    - Pyro4
    - aenum
    - anytree
    - cython
    - dask
    - descartes
    - geopandas
    - google-auth
    - google-auth-oauthlib
    - google-api-python-client
    - google-cloud-datastore
    - google-cloud-storage
    - markdown
    - matplotlib-base
    - natcap.invest
    - netcdf4
    - numpy
    - openpyxl
    - gdal
    - pandas
    - pandoc
    - pygeoprocessing
    - pyqt
    - python
    - python-pptx
    - pyyaml
    - qtawesome
    - qtpy
    - rioxarray
    - scikit-learn
    - scipy
    - seaborn
    - setuptools >=70
    - setuptools_scm
    - shapely
    - sip
    - six
    - statsmodels
    - taskgraph
    - tqdm
    - xarray
    - xlrd
    - libgdal-hdf5


test:
  imports:
    - hazelbean
    - hazelbean.calculation_core
    - hazelbean.ui
  requires:
    - pip

about:
  home: https://github.com/jandrewjohnson/hazelbean_dev
  summary: Geospatial research tools
  license: CC-BY-NC-SA-4.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - phargogh
    - jandrewjohnson
