{% set name = "hazelbean" %}
{% set version = "1.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hazelbean-{{ version }}.tar.gz
  sha256: 43cda7cf51ed5a57b3bf32665f572ff245e84a33d977e85fcc42eb0e13b99466
  patches:
      - 0001-remove-unnecessary-fiona-import.patch

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  skip: True  # [py>=312]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - python      # [build_platform != target_platform]
    - cython <3   # [build_platform != target_platform]
    - numpy       # [build_platform != target_platform]
  host:
    - python
    - pip
    - cython <3
    - numpy
    - setuptools
    - setuptools_scm
  run:
    - Pyro4
    - aenum
    - anytree
    - dask
    - descartes
    - geopandas
    - google-cloud-datastore
    - google-cloud-storage
    - markdown
    - matplotlib-base
    - netcdf4
    - numpy
    - openpyxl
    - gdal
    - pandas
    - pandoc
    - pygeoprocessing
    - pyqt
    - python
    - pyyaml
    - qtawesome
    - qtpy
    - rioxarray
    - scikit-learn
    - scipy
    - seaborn
    - shapely
    - sip
    - six
    - statsmodels
    - taskgraph
    - xarray
    - xlrd

  # Packages that are optional at runtime but must match a specification when installed.
  run_constrained:
      - natcap.invest ==3.11.0


test:
  imports:
    - hazelbean
    - hazelbean.calculation_core
    - hazelbean.ui
  requires:
    - pip

about:
  home: https://github.com/jandrewjohnson/hazelbean_dev
  summary: Geospatial research tools
  license: CC-BY-NC-SA-4.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - phargogh
    - jandrewjohnson
